name: Build Snapshots
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
permissions:
  contents: write
jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Build Package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: iris
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Iris
          path: build/libs/*.jar
          if-no-files-found: error
